# Model configuration
model_path: baseline/baseline_model.pth
num_epochs: 250
learning_rate: 0.0004
weight_decay: 0.0001
feature_extractor: efficientnet_b4  # Options: resnet50, efficientnet_b4

# Training data configuration
train:
  meta_file: ./chunks_scaled_3/metadata/train_metadata.json
  batch_size: 64
  workers: 8
  input_size: [224, 224]
  hflip: True
  vflip: True
  rotate: True
  image_path: chunks_scaled_3

# Testing data configuration
test:
  meta_file: ./chunks_scaled_3/metadata/test_metadata.json
  batch_size: 1 # must always be 1 for test loader
  workers: 2
  input_size: [224, 224]
  image_path: chunks_scaled_3

scheduler:
  name: 'none'  # Options: 'step', 'plateau', 'none' - none will gradually drop the learning rate every time the model goes above 85% or 90% accuracy
  step:
    step_size: 10
    gamma: 0.5
  plateau:
    factor: 0.2
    patience: 4
    mode: 'max'