# baseline_config.yaml

# Model configuration
model_path: improved_baseline/DVNet.pth
num_epochs: 40 
learning_rate: 0.001
weight_decay: 0.0001

# Training data configuration
train:
  meta_file: ./chunks_scaled_2/metadata/train_metadata.json
  batch_size: 32
  workers: 8
  input_size: [224, 224]
  hflip: False
  vflip: False
  rotate: False
  image_path: chunks_scaled_2

# Testing data configuration
test:
  meta_file: ./chunks_scaled_2/metadata/test_metadata.json
  batch_size: 1 # must always be 1 for test loader
  workers: 2
  input_size: [224, 224]
  image_path: chunks_scaled_2
