path: UOG_1996
output_path: chunks/UOG_1996/
files:
  -
    name: orthos/raster.tif
    dimensions: 1

mask: .\data\UOG_1996\mask_1996.tif
reference: .\data\UOG_1996\orthos\raster.tif
chunk_size: 90
chunk_overlap: 20
anomaly_threshold: 0.7
normal_threshold: 0.0
scale_ratio: 0.5
---
path: UOG_1676
output_path: chunks/UOG_1676/
files:
  -
    name: orthos/raster.tif
    dimensions: 1

mask: .\data\UOG_1676\mask_1676.tif
reference: .\data\UOG_1676\orthos\raster.tif
chunk_size: 90
chunk_overlap: 20
anomaly_threshold: 0.7
normal_threshold: 0.0
scale_ratio: 0.5
---
path: UOG_2057
output_path: chunks/UOG_2057/
files:
  -
    name: orthos/raster.tif
    dimensions: 1

mask: .\data\UOG_2057\mask_2057.tif
reference: .\data\UOG_2057\orthos\raster.tif
chunk_size: 90
chunk_overlap: 20
anomaly_threshold: 0.7
normal_threshold: 0.0
scale_ratio: 0.5
---
path: UOG_1883
output_path: chunks/UOG_1883/
files:
  -
    name: orthos/raster.tif
    dimensions: 1

mask: .\data\UOG_1883\mask_1883.tif
reference: .\data\UOG_1883\orthos\raster.tif
chunk_size: 90
chunk_overlap: 20
anomaly_threshold: 0.7
normal_threshold: 0.0
scale_ratio: 0.5
---
path: UOG_2223
output_path: chunks/UOG_2223/
files:
  -
    name: orthos/raster.tif
    dimensions: 1

mask: .\data\UOG_2223\mask_2223.tif
reference: .\data\UOG_2223\orthos\raster.tif
chunk_size: 90
chunk_overlap: 20
anomaly_threshold: 0.7
normal_threshold: 0.0
scale_ratio: 0.5
---
path: UOG_2227
output_path: chunks/UOG_2227/
files:
  -
    name: orthos/raster.tif
    dimensions: 1

mask: .\data\UOG_2227\mask_2227.tif
reference: .\data\UOG_2227\orthos\raster.tif
chunk_size: 90
chunk_overlap: 20
anomaly_threshold: 0.7
normal_threshold: 0.0
scale_ratio: 0.5