input:
  target_filename: orthomosaic_visible.tif

downscaling:
  target_size: [4096, 4096]
  chunk_size: 4096
  overlap: 128
  num_workers: 12

segmentation:
  sam_checkpoint: "sam-segmentation/sam_vit_l_0b3195.pth"
  model_type: "vit_l"
  pixel_value_threshold: 0.3
  min_segment_size: 0.014
  pred_iou_thresh: 0.07
  stability_score_thresh: 0.88
  box_nms_thresh: 0.4
  crop_nms_thresh: 0.4
  sam_target_size: [1024, 1024]
  nodata_value: [0, 0, 0, 0]
  max_nodata_percentage: 0.01
  border_size: 50
  outlier_threshold: 1.5 # for dam detection
  color_thresholds:
    lower_green: [30, 40, 40]
    upper_green: [80, 245, 200]
  morphology:
    kernel_size: 7
