# Input file settings
input:
  target_filename: "orthomosaic_visible.tif"  # Name of the target file to process

# Downscaling settings
downscaling:
  target_size: [4064, 4064]  # Target size for downscaled image [height, width]
  chunk_size: 4096  # Size of chunks for processing large images
  num_workers: 12  # Number of worker processes (0 for all available cores)
  overlap: 128  # Overlap between chunks to avoid edge artifacts

# Segmentation settings
segmentation:
  # Color thresholds for initial segmentation
  color_thresholds:
    lower_green: [30, 40, 40]  # Lower bound of green color in HSV
    upper_green: [80, 255, 200]  # Upper bound of green color in HSV

  # Morphological operations
  morphology:
    kernel_size: 3 # Size of kernel for morphological operations

  # Size thresholds for segment filtering
  size_thresholds:
    min_segment_ratio: 0.014  # Minimum size ratio for segments to keep

  # Shape thresholds for segment filtering
  shape_thresholds:
    min_circularity: 0.01  # Minimum circularity for segments to keep

  # Adaptive closing parameters
  adaptive_closing:
    max_kernel_size: 30  # Maximum size for the closing kernel
    kernel_step: 6  # Step size for increasing the kernel
    large_segment_threshold: 0.03  # Threshold for large segments
    min_large_segments: 3  # Minimum number of large segments needed before stopping

  # Buffer settings
  buffer:
    size: 10  # Size of the buffer to add around each mask

  # Hole filling parameters
  hole_filling:
    small_hole_max_size: 0.0003  # Maximum size of holes to fill (as a fraction of total area)

  # Segment separation parameters
  segment_separation:
    max_connection_width: 100  # Maximum width of connections to separate
    min_segment_size_percentage: 0.002  # Minimum size of separated segments (as a fraction of original)
    max_recursion_depth: 3  # Maximum recursion depth for segment separation

  # No-data removal parameters
  nodata_removal:
    nodata_value: [0, 0, 0, 0]  # Value representing no-data pixels
    nodata_threshold: 15000  # Maximum number of no-data pixels allowed
    max_nodata_percentage: 0.15  # Maximum percentage of no-data pixels allowed in a segment
    border_size: 100  # Size of border to add when checking for no-data pixels